services:
    _defaults:
        public: true

    abc.module_a.your_service:
        class: PrestaShop\Module\Modulea\YourService
        abstract: true

    abc.child_service:
        class: PrestaShop\Module\Abc\ChildService
        parent: abc.module_a.your_service
